---
- name: Deploy Squid proxy agent
  hosts: target_machines
  become: true
  tasks:
    - name: Install Python on Linux
      raw: test -e /usr/bin/python || (apt -y update && apt install -y python-minimal)
      when: ansible_facts['ansible_system'] == 'Linux'
      
    - name: Install Python on Windows
      win_chocolatey:
        name: python
        state: present
      when: ansible_facts['ansible_system'] == 'Windows'
      
    - name: Install Flask
      pip:
        name: flask
      when: ansible_facts['ansible_system'] == 'Linux'
        
    - name: Install Squid on Linux
      apt:
        name: squid
        state: present
      when: ansible_facts['ansible_system'] == 'Linux'
        
    - name: Install Squid on Windows
      win_chocolatey:
        name: squid
        state: present
      when: ansible_facts['ansible_system'] == 'Windows'
        
    - name: Copy agent script
      copy:
        src: agent.py
        dest: /opt/agent.py
      when: ansible_facts['ansible_system'] == 'Linux' 
        
    - name: Copy agent script on Windows
      win_copy:
        src: agent.py
        dest: C:\agent.py
      when: ansible_facts['ansible_system'] == 'Windows'
        
    - name: Configure Squid proxy
      uri:
        url: http://localhost:5001/configure
        method: POST
        body_format: form-urlencoded
        body:
          config: "{{ lookup('file', 'squid.conf') }}"
      when: ansible_facts['ansible_system'] == 'Linux'
          
    - name: Open port for Squid proxy configuration on Linux
      ufw:
        rule: allow
        port: 5001
        proto: tcp
        state: enabled
      when: ansible_facts['ansible_system'] == 'Linux'
      
    - name: Open port for Squid proxy configuration on Windows
      win_firewall_rule:
        name: Allow Squid Proxy Configuration
        localport: 5001
        action: allow
        protocol: TCP
      when: ansible_facts['ansible_system'] == 'Windows'

    - name: Start Squid service on Linux
      service:
        name: squid
        state: started
        enabled: yes
      when: ansible_facts['ansible_system'] == 'Linux'

    - name: Start Squid service on Windows
      win_service:
        name: squid
        start_mode: auto
        state: started
      when: ansible_facts['ansible_system'] == 'Windows'

    - name: Run agent script
      command: python /opt/agent.py
      args:
        chdir: /opt
      when: ansible_facts['ansible_system'] == 'Linux'
